//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeService.DataAccess.SqlScripts {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Sql {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Sql() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EmployeeService.DataAccess.SqlScripts.Sql", typeof(Sql).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на INSERT INTO &quot;Companies&quot; (&quot;Name&quot;)
        ///VALUES (@Name)
        ///RETURNING &quot;Id&quot;;.
        /// </summary>
        internal static string AddCompany {
            get {
                return ResourceManager.GetString("AddCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на INSERT INTO &quot;Departments&quot; (&quot;CompanyId&quot;,&quot;Name&quot;,&quot;Phone&quot;)
        ///VALUES (@CompanyId,@Name,@Phone)
        ///RETURNING &quot;Id&quot;;.
        /// </summary>
        internal static string AddDepartment {
            get {
                return ResourceManager.GetString("AddDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на INSERT INTO &quot;Employees&quot; (&quot;Name&quot;,&quot;Surname&quot;,&quot;Phone&quot;,&quot;CompanyId&quot;,&quot;PassportId&quot;,&quot;DepartmentId&quot;)
        ///VALUES (@Name,@Surname,@Phone,@CompanyId,@PassportId,@DepartmentId)
        ///RETURNING &quot;Id&quot;;.
        /// </summary>
        internal static string AddEmployee {
            get {
                return ResourceManager.GetString("AddEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на INSERT INTO &quot;Passports&quot; (&quot;Type&quot;,&quot;Number&quot;)
        ///VALUES (@Type,@Number)
        ///RETURNING &quot;Id&quot;;.
        /// </summary>
        internal static string AddPassport {
            get {
                return ResourceManager.GetString("AddPassport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SELECT count(1) 
        ///FROM &quot;Companies&quot; 
        ///WHERE &quot;Id&quot; = @Id;.
        /// </summary>
        internal static string CompanyExists {
            get {
                return ResourceManager.GetString("CompanyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на DELETE FROM &quot;Companies&quot;
        ///WHERE &quot;Id&quot; = @Id;.
        /// </summary>
        internal static string DeleteCompany {
            get {
                return ResourceManager.GetString("DeleteCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на DELETE FROM &quot;Departments&quot;
        ///WHERE &quot;Id&quot; = @Id;.
        /// </summary>
        internal static string DeleteDepartment {
            get {
                return ResourceManager.GetString("DeleteDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на DELETE FROM &quot;Employees&quot;
        ///WHERE &quot;Id&quot; = @Id;.
        /// </summary>
        internal static string DeleteEmployee {
            get {
                return ResourceManager.GetString("DeleteEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на DELETE FROM &quot;Passports&quot;
        ///WHERE &quot;Id&quot; = @Id;.
        /// </summary>
        internal static string DeletePassport {
            get {
                return ResourceManager.GetString("DeletePassport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SELECT count(1)
        ///FROM &quot;Departments&quot;
        ///WHERE &quot;Id&quot; = @Id;.
        /// </summary>
        internal static string DepartmentExists {
            get {
                return ResourceManager.GetString("DepartmentExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SELECT count(1)
        ///FROM &quot;Employees&quot;
        ///WHERE &quot;Id&quot; = @Id;.
        /// </summary>
        internal static string EmployeeExists {
            get {
                return ResourceManager.GetString("EmployeeExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SELECT &quot;Id&quot;,&quot;Name&quot;,&quot;Surname&quot;,&quot;Phone&quot;,&quot;CompanyId&quot;,&quot;PassportId&quot;,&quot;DepartmentId&quot;
        ///FROM &quot;Employees&quot;;.
        /// </summary>
        internal static string GetAllEmployees {
            get {
                return ResourceManager.GetString("GetAllEmployees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SELECT &quot;Id&quot;,&quot;Name&quot;
        ///FROM &quot;Companies&quot; 
        ///WHERE &quot;Id&quot; = @Id;.
        /// </summary>
        internal static string GetCompany {
            get {
                return ResourceManager.GetString("GetCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SELECT &quot;Id&quot;,&quot;CompanyId&quot;,&quot;Name&quot;,&quot;Phone&quot;
        ///FROM &quot;Departments&quot;
        ///WHERE &quot;Id&quot; = @Id;.
        /// </summary>
        internal static string GetDepartment {
            get {
                return ResourceManager.GetString("GetDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SELECT &quot;Id&quot;,&quot;Name&quot;,&quot;Surname&quot;,&quot;Phone&quot;,&quot;CompanyId&quot;,&quot;PassportId&quot;,&quot;DepartmentId&quot;
        ///FROM &quot;Employees&quot;
        ///WHERE &quot;Id&quot; = @Id;.
        /// </summary>
        internal static string GetEmployee {
            get {
                return ResourceManager.GetString("GetEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SELECT &quot;Id&quot;,&quot;Name&quot;,&quot;Surname&quot;,&quot;Phone&quot;,&quot;CompanyId&quot;,&quot;PassportId&quot;,&quot;DepartmentId&quot;
        ///FROM &quot;Employees&quot;
        ///WHERE &quot;CompanyId&quot; = @CompanyId;.
        /// </summary>
        internal static string GetEmployeesByCompanyId {
            get {
                return ResourceManager.GetString("GetEmployeesByCompanyId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SELECT &quot;Id&quot;,&quot;Name&quot;,&quot;Surname&quot;,&quot;Phone&quot;,&quot;CompanyId&quot;,&quot;PassportId&quot;,&quot;DepartmentId&quot;
        ///FROM &quot;Employees&quot;
        ///WHERE &quot;DepartmentId&quot; = @DepartmentId;.
        /// </summary>
        internal static string GetEmployeesByDepartmentId {
            get {
                return ResourceManager.GetString("GetEmployeesByDepartmentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SELECT &quot;Id&quot;,&quot;Type&quot;,&quot;Number&quot;
        ///FROM &quot;Passports&quot;
        ///WHERE &quot;Id&quot; = @Id;.
        /// </summary>
        internal static string GetPassport {
            get {
                return ResourceManager.GetString("GetPassport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SELECT count(1)
        ///FROM &quot;Passports&quot;
        ///WHERE &quot;Id&quot; = @Id;.
        /// </summary>
        internal static string PassportExists {
            get {
                return ResourceManager.GetString("PassportExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на UPDATE &quot;Companies&quot;
        ///SET 
        ///    &quot;Name&quot; = @Name
        ///WHERE &quot;Id&quot; = @Id;.
        /// </summary>
        internal static string UpdateCompany {
            get {
                return ResourceManager.GetString("UpdateCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на UPDATE &quot;Departments&quot;
        ///SET
        ///    &quot;CompanyId&quot; = CASE WHEN @CompanyId = 0 then &quot;CompanyId&quot; ELSE @CompanyId END,
        ///    &quot;Name&quot; = CASE WHEN @Name is NULL then &quot;Name&quot; ELSE @Name END,
        ///    &quot;Phone&quot; = CASE WHEN @Phone is NULL then &quot;Phone&quot; ELSE @Phone END
        ///WHERE &quot;Id&quot; = @Id;.
        /// </summary>
        internal static string UpdateDepartment {
            get {
                return ResourceManager.GetString("UpdateDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на UPDATE &quot;Employees&quot;
        ///SET
        ///    &quot;Name&quot; = CASE WHEN @Name is NULL then &quot;Name&quot; ELSE @Name END,
        ///    &quot;Surname&quot; = CASE WHEN @Surname is NULL then &quot;Surname&quot; ELSE @Surname END,
        ///    &quot;Phone&quot; = CASE WHEN @Phone is NULL then &quot;Phone&quot; ELSE @Phone END,
        ///    &quot;CompanyId&quot; = CASE WHEN @CompanyId = 0 then &quot;CompanyId&quot; ELSE @CompanyId END,
        ///    &quot;DepartmentId&quot; = CASE WHEN @DepartmentId = 0 then &quot;CompanyId&quot; ELSE @DepartmentId END,
        ///    &quot;PassportId&quot; = CASE WHEN @PassportId = 0 then &quot;PassportId&quot; ELSE @PassportId END
        ///WHERE &quot;Id&quot; = @I [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string UpdateEmployee {
            get {
                return ResourceManager.GetString("UpdateEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на UPDATE &quot;Passports&quot;
        ///SET
        ///    &quot;Type&quot; = CASE WHEN @Type is NULL then &quot;Type&quot; ELSE @Type END,
        ///    &quot;Number&quot; = CASE WHEN @Number is NULL then &quot;Number&quot; ELSE @Number END
        ///WHERE &quot;Id&quot; = @Id;.
        /// </summary>
        internal static string UpdatePassport {
            get {
                return ResourceManager.GetString("UpdatePassport", resourceCulture);
            }
        }
    }
}
